### ISSUE TITLE
Add ability to delete a secret/url [Enhancement] 

### ISSUE THREAD

**Issue by erreip** [mrclay/SecretMark#5]

**Comment by mrclay** [comment]
What does this mean?

**Comment by erreip** [comment]
Once a secret/url is created, can it there be a way to delete it so that even if the key is entered, the secret is not accessible?

**Comment by mrclay** [comment]
No. The page has no memory of anything entered and no data touches the server.

**Comment by erreip** [comment]
Understood. So the secret is encrypted and encoded into the URL and the page simply decrypts the secret from this URL, it doesn't actually store anything. Super elegant!

Cheers,
